accessing
throwTimeoutError: anObject

	throwTimeoutError := anObject